sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zamfirdc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zamfirdc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-471112974477"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

